### ISSUE TITLE
Adding secret support for Feathr Online

### ISSUE THREAD

**Issue by blrchen** [feathr-ai/helm-charts#9]

**Comment by ahlag** [comment]
## Research

1. Use the Azure Key Vault Provider for Secrets Store CSI Driver in an AKS cluster (https://learn.microsoft.com/en-us/azure/aks/csi-secrets-store-driver)
1. Provide an identity to access the Azure Key Vault Provider for Secrets Store CSI Driver (https://learn.microsoft.com/en-us/azure/aks/csi-secrets-store-identity-access)

Tasks:
- [x] Use helm for secrets, this step is cloud agnostic, with this step, we are using k8s standard way for secrets
- [ ] Integrate with azure key vault, this step only works if deployment target is aks, this will leverage Azure Key Vault for advanced secret features.
